### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by Orisphera** [zeque92/RealTime3DwithPython#3]
I tried to run the programs in this project and found several issues, some of which make some programs not start.
- There are chdir calls to folders that don't exist. The strings provided as arguments contain invalid escape characters. Removing the chdir calls solves the problem.
- Some files are not present in some folders with the programs that need them.
- Some files are seem to have incorrect names:
 - Guru in Sound Vision and Texture Mapping and Alphaks in Texture Mapping have the extension specified as ".jpg" in code and ".JPG" in files.
 - Alien Boss files in Space Invaders are capitalized in files, but not in code.
 - I have copied them and now have two copies of each: one with the correct name and one with the incorrect name.
- RGBSphere doesn't respond while adding depth in RGBSphere.__init__
- After that, it throws numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'. Changing the data type in color to float makes it first fill the map with lighter triangles and then show rotating icosahedron without a map on it.

**Comment by zeque92** [comment]
Hi Orisphera,

Thanks a lot for pointing out these issues. 

- Using _chdir_ was due to my misunderstanding when I started the project. I have not used it in any of the more recent programs, and would advise any users to just remove the line. Sorry about this.
- In the only OS I have to available test the programs - Windows 11 (running Spyder 4) - the file names are not case sensitive and, hence, work. My apologies to anyone getting error messages due to e.g. jpg != JPG.
- The same goes for RGBSphere - I can not replicate the error you describe. The program starts with mapping colors from a world map, and then shows a grid icosahedron by default. Color & map are only added when changing program mode (cursor keys, instructions on the left).
- I also received a comment on Space Invaders from a MacOS user, who was not able to hit the bosses _at all_ before making the defined "hit areas" a little larger. Apparently the OS independence does not always work 100 %.
